spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
      url: jdbc:postgresql://localhost:5432/productServiceDB?createDatabaseIfNotExist=true&useSSL=true
      username: postgres
      password: Password1
  jpa:
    hibernate:
      ddl-auto: create-drop
  properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always




